# Generated by Django 2.1.3 on 2019-04-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelmetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('x_central_point', models.FloatField(max_length=20)),
                ('y_central_point', models.FloatField(max_length=20)),
                ('rect_width', models.FloatField(max_length=20)),
                ('rect_height', models.FloatField(max_length=20)),
                ('is_wearing', models.CharField(max_length=10)),
                ('mark_flag', models.CharField(max_length=10)),
                ('tag_judgement', models.CharField(max_length=10)),
            ],
        ),
    ]
