# Generated by Django 2.1.3 on 2019-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ams', '0002_helmetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=200)),
                ('img_origin_id', models.FloatField(max_length=20)),
                ('x_block_index', models.FloatField(max_length=20)),
                ('y_block_index', models.FloatField(max_length=20)),
                ('img_size', models.FloatField(max_length=20)),
                ('img_type', models.FloatField(max_length=20)),
                ('mark_flag', models.CharField(max_length=10)),
            ],
        ),
    ]
